// This file is automatically generated. Do not edit it directly. 
// ^^^ This comment usually comes FROM the supabase gen types command if you output directly to this file.
// If this client.ts is YOUR file, then the comment might be misleading.
// The important part is that 'Database' comes from the generated types file.

import { createClient } from '@supabase/supabase-js';
import { Database } from '@/types/supabase'; // REMINDER: Ensure this file exists after running Supabase CLI type generation
const SUPABASE_URL = "https://vctpcmuqyvzeytmoukxv.supabase.co";
const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY; // Ensure this env var is set

if (!SUPABASE_ANON_KEY) {
  throw new Error("Missing Supabase anon key. Ensure NEXT_PUBLIC_SUPABASE_ANON_KEY is set.");
}
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
